name: Android Release Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        compile-sdk: [29]
        build-tools: [29.0.2]
        sdk-tools:   [4333796]

    steps:
      - uses: actions/checkout@v1
      - name: setup ubuntu
        run: |
          sudo apt-get --quiet update --yes
          sudo apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
      - name: setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Android SDK
        run: |
          wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${{ matrix.sdk-tools }}.zip
          unzip -d android-sdk-linux android-sdk.zip
          sudo mkdir -p /root/.android
          sudo touch /root/.android/repositories.cfg
          echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${{ matrix.compile-sdk }}" >/dev/null
          echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
          echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${{ matrix.build-tools }}" >/dev/null
          export ANDROID_HOME=$PWD/android-sdk-linux
          export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
          chmod +x ./gradlew
          set +o pipefail
          yes | android-sdk-linux/tools/bin/sdkmanager --licenses
          set -o pipefail
      - name: Setup Build Configs
        run: |
          echo "RELEASE_STORE_FILE=`pwd`/application.keystore" >> ./local.properties
          echo "RELEASE_STORE_PASSWORD=${{ secrets.AndroidBuildPassword }}" >> ./local.properties
          echo "RELEASE_KEY_ALIAS=key0" >> ./local.properties
          echo "RELEASE_KEY_PASSWORD=${{ secrets.AndroidBuildPassword }}" >> ./local.properties
          echo "${{ secrets.GoogleServicesJson }}" >> ./app/google-services.json
      - name: Android Release Build
        run: |
          ./gradlew assembleRelease
      - uses: actions/upload-artifact@master
        with:
          name: outputs
          path: app/build/outputs/